### ISSUE TITLE
RuntimeError: Failed to add edge detection

### ISSUE THREAD

**Issue by Folmaland** [thecode/ha-rpi_gpio#109]
Hello,

I'm using this addon for a long time, but just got error that I don't know how to solve. 
This happened when I made a backup of a HA and restored it in another RPI (Both are 4 B). There was 2 binary sensors described, but I had to change the ID. After doing that I got this error. If I change back the ID error is gone, but the problem is I must find a way to change them.
P.S. If I paste code example of binary sensor I still get the error.

Thank you for your help

![image](https://user-images.githubusercontent.com/102060910/193216110-730f6526-7255-46ac-a76b-0bfb92e5c853.png)
![image](https://user-images.githubusercontent.com/102060910/193216407-4394adf2-0f37-43e0-b1b2-2d416836598b.png)

**Comment by pdivers** [comment]
I'm getting this same thing now. Any suggestions?
