### ISSUE TITLE
GPiO 7 and 8 are not allowed as a binary_sensor

### ISSUE THREAD

**Issue by majbah-ha** [thecode/ha-rpi_gpio#121]
Hi,

I found that if you enter GPIO 7 and / or GPIO 8 as a binary_sensor the configuration will brake. Please verify if this is correct..

Thanks in advance

**Comment by thecode** [comment]
See here : https://raspberrypi.stackexchange.com/questions/13898/how-to-use-gpio7-8
They are used by the OS, you can disable this as explained there.
