### ISSUE TITLE
from homeassistant.components import rpi_gpio

### ISSUE THREAD

**Issue by wvoigt** [thecode/ha-rpi_gpio#13]
I'm a newbie in reading home assistant code, so this may be way off base and a dumb question.
But in binary_sensor.py, cover.py, and switch.py, I see the following line:
`from homeassistant.components import rpi_gpio`

Won't this go away once rpi_gpio is removed as a default component in home assistant?
Should it point to this custom_component?  Or does this custom component show up under homeassistant.components once installed?

I'm assuming you want this instance of rpi_gpio to be running stand alone prior to the actual removal of the original.  So everyone can be testing it and confident that it is working before the transition.

**Comment by thecode** [comment]
Thanks for spotting this, we recently started fixing integrations in core not to use `from homeassistant.components import` but use relative imports (e.g. `from . import`) exactly for this reason. I will fix and release a new version.

**Comment by dsegantx** [comment]
Wendel you are my new HERO!  Great work
