### ISSUE TITLE
Remanent Outputs

### ISSUE THREAD

**Issue by toolCollection92** [thecode/ha-rpi_gpio#140]
Hi, i was wondering if this is a issue with Homeassistant or this plugin, but i use the GPIO to drive relays for my appliances (TV, Audio, PC etc.) and at each homeassistant restart (altered configuration.yaml needs the full restart) all pins will turn off.
Is there a possibility to make the gpio pins remanent?

**Comment by thecode** [comment]
It is not possible, the GPIOs are reset by the driver. If you need the pins to keep their state between restarts I highly suggest to use ESP based board with ESPHome/Tasmota or a Shelly device.
