### ISSUE TITLE
.button integration

### ISSUE THREAD

**Issue by Sammerdan** [thecode/ha-rpi_gpio#17]
I'm actually happy this is now in the community hands.

I'm using the same rpi to run Hass and to controll many things.

One thing it does is controlling some switch latches (Puls to switch) over the GPIO. 
After this update I was afraid it would be gone, but thanks to you it won't!

Now my question:
The best thing for me would if the GPIO could do a button "Pulse".

Now I configured them as switch --> touched and an automation turns off directly. 
Then I have the pulse.

But it would be great if the "button" would be possible. So just a quick close of the relay and open again.

Possible?

Thanks!

**Comment by thecode** [comment]
This is already possible using scripts. A script can run from a button, turn on the switch, make a short delay and turn off.
I prefer to keep issues for bugs not for feature requests. If you need help with creating this using a script feel free to contact me on [Discord](https://discord.gg/c5DvZ4e) or create a post in the [Community Forum](https://community.home-assistant.io) so others will be able to propose and help with their implementations for this.
Thanks! 👍
