### ISSUE TITLE
MCP23017 integration or RPI-GPIO with I2C? 

### ISSUE THREAD

**Issue by gugaspinto** [thecode/ha-rpi_gpio#20]
Hello
I use MCP23017 integration for a long time ago. 
My home alarm is very stable using this integration and a all wired network sensors and switches. 
(In the alarm system I prefer wired sensors and switches) 

As I understood, we will loose it. 
Is it possible to have MCP23017 integration in HACS?
This RPI-GPIO could have I2C? 

Or I need to think about change my hardware... 
Thanks for your work and contributions

**Comment by thecode** [comment]
The MCP23017 is a different integration, it is not related to the RPI-GPIO integration.
For now I am only adding integrations I have the hardware to test my changes on as I don't believe in supporting an integration I can't test the code myself.
I will consider buying a MCP23017 and adding support for it.

**Comment by darmach** [comment]
@gugaspinto Also this might suit you (but I'm going to track this one :D)

**Comment by gugaspinto** [comment]
Thanks... 
Probably it solves my situation.. 
Very thanks for you attention
