### ISSUE TITLE
pigpio Daemon PWM LED support

### ISSUE THREAD

**Issue by JustNoLimit** [thecode/ha-rpi_gpio#21]
Hello, thank you for your effort. I am controlling my RGB LED Strip with rpi gpio will this feature be added to this integration too

**Comment by bennop** [comment]
Was looking for that, too.

@JustNoLimit: Just wondering, how do you do it in rpi gpio? The documentation page does not list PWM as an option?

**Comment by thecode** [comment]
The pigpio PWM is a different integration, it is not related to the GPIO integration, you will have to wait for someone to pick it up and maintain it.

**Comment by darmach** [comment]
Ah, a pity, we could use a one GPIO integration to rule them all ;)
I personally was hoping to get pwm fan control on HAOS on Rpi :)

**Comment by thecode** [comment]
It is not possible to make "one integration to rule them all", every integration has different syntax and requirements. Even if I do workaround to make multiple integrations under one integration it will force users to install all requirements and limit the usable OS which can use the integration.

The PWM integration as a requirement which needs OS support, so it would not be possible to support it under Home Assistant OS without adding support in the OS.
