### ISSUE TITLE
No more sensors after YAML reload

### ISSUE THREAD

**Issue by Patbonamy** [thecode/ha-rpi_gpio#222]
Hello,
After YAML configuration reloading trough Developer Tools, the sensors are all unavailable. Doing a full restart on HA restores them.
Please Help.
Regards

**Comment by resnbl** [comment]
I noticed the same issue today. Just guessing here, but I suspect this has something to do with defining a binary_sensor in the main config yaml - is there some  other place it can be placed that will cause this to operate as expected?

(I am using the rpi-gpio addon to detect the big pushbutton on what was formerly a Google AYI box and is now my HA system.)

**Comment by Patbonamy** [comment]
> I noticed the same issue today. Just guessing here, but I suspect this has something to do with defining a binary_sensor in the main config yaml - is there some other place it can be placed that will cause this to operate as expected?
> 
> (I am using the rpi-gpio addon to detect the big pushbutton on what was formerly a Google AYI box and is now my HA system.)

For me I have a binary_sensors.yaml file, I notice when I reload the gpio entities in yaml Developer Tools I have the issue.

**Comment by jnnsrctr** [comment]
Same issue here... It's really annoying to have to restart HA every time instead of a quick YAML reload.
@thecode I know the integration is deprecated, but is there maybe someone who can look into this? There must be an easy solution for this...

**Comment by thecode** [comment]
I have looked into it and unfortunately without major rewrite it won't work as it is now. If I would do a rewrite than it would be to move it into config flow, someone already started working on it, but didn't finish all the platforms: https://github.com/thecode/ha-rpi_gpio/pull/112
