### ISSUE TITLE
DHT22

### ISSUE THREAD

**Issue by ashrafmn** [thecode/ha-rpi_gpio#23]
Hi,, 
I couldn't find the configuration for the binary sensor DHT22.
How can i configure my DHT22 which is connected to GPIO 04 in Raspberry pi?

**Comment by thecode** [comment]
This replaced the GPIO integration, the DHT22 is a different integration. For now I try to focus on hardware that I have and can test, it would be better to wait for a developer which use DHT22 to take maintain of the DHT22 integration.

**Comment by ashrafmn** [comment]
thanks for the response,, well I'm connecting (wiring) the DHT22 through raspberry pi GPIO.
So will this work for now, or we still need this to be developed?

**Comment by thecode** [comment]
It will not work unless a developer picks it up and add it as a custom integration.

**Comment by ashrafmn** [comment]
clear,, 
so nothing else to do now except waiting for someone to get this developed... :(

thanks.

**Comment by lpt2007** [comment]
same problem here, any news

**Comment by thecode** [comment]
> same problem here, any news

News will be when a developer picks it up, I am only maintaining the GPIO integration: https://www.home-assistant.io/integrations/rpi_gpio/
