### ISSUE TITLE
Not working on Raspberry Pi5

### ISSUE THREAD

**Issue by JarnoMarinelli** [thecode/ha-rpi_gpio#246]
Hi,

for performance and RAM requirements of all my addons and integrations I decided to put my homeassistant instance on the new Pi5 with 8GB of RAM. How I still used this older integration to send an input to a remote, in order to open my gate, since that is shared and cannot be made smart in any other way.
Can someone figure out what needs to be changed on the new Pi5 hardware, in order to use a switch entity with this addon?

Here the errore I get on startup:
Error while setting up rpi_gpio platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/switch.py", line 69, in setup_platform
    RPiGPIOSwitch(
  File "/config/custom_components/rpi_gpio/switch.py", line 100, in __init__
    setup_output(self._port)
  File "/config/custom_components/rpi_gpio/__init__.py", line 39, in setup_output
    GPIO.setup(port, GPIO.OUT)
RuntimeError: Cannot determine SOC peripheral base address

**Comment by elik745i** [comment]
Same here I control my relays using GPIO header and cant use RPI5 for that. Is there a way?

**Comment by thecode** [comment]
See https://github.com/thecode/ha-rpi_gpio/issues/225#issuecomment-1892114570
The current library `RPi.GPIO` did not add support for Raspberry PI 5 so there is nothing I can do. I don't have PI 5 and migrating to another library without the option to test my changes is not something I do. Someone try to replace to another library in the linked comment, I don't know what the status of it.

**Comment by JarnoMarinelli** [comment]
> See [#225 (comment)](https://github.com/thecode/ha-rpi_gpio/issues/225#issuecomment-1892114570) The current library `RPi.GPIO` did not add support for Raspberry PI 5 so there is nothing I can do. I don't have PI 5 and migrating to another library without the option to test my changes is not something I do. Someone try to replace to another library in the linked comment, I don't know what the status of it.

I found a drop-in replacement library.
https://rpi-lgpio.readthedocs.io/en/release-0.4/index.html
Can you maybe create a fork for pi5 and share the repository with me, so that i can test it?

**Comment by thecode** [comment]
> I found a drop-in replacement library. https://rpi-lgpio.readthedocs.io/en/release-0.4/index.html Can you maybe create a fork for pi5 and share the repository with me, so that i can test it?

I don't understand what you ask, you can fork this repository from the GitHub interface, you don't need me to do it (and I can't)
