### ISSUE TITLE
On restart it does not restore the previous state of the outputs

### ISSUE THREAD

**Issue by ik1zyq** [thecode/ha-rpi_gpio#25]
When Home Assistant (Raspberry PI3 B) is restarted, GPIO does not maintain the state of the outputs set before the restart. Is this normal or is there a way to correct the problem?

**Comment by thecode** [comment]
This is not part of this integration. The integration is simply mapping the hardware GPIOs to Home Assistant sensors or switches, when you reboot the device the GPIO reverts to it's default state and the integration show the correct state. Integrations in general are meant to represent hardware or device state and should not manipulate the state. 

If you need to maintain a state after device reboot I highly recommend using an external device to control the IO, such as Tasmota or ESPHome, these devices can store the last state on non volatile memory and are not depended on the server state.
