### ISSUE TITLE
not working with working with a raspberry pi 5, 2024.5.1?

### ISSUE THREAD

**Issue by GitTimRoben** [thecode/ha-rpi_gpio#253]
working with a raspberry pi 5,
Core: 2024.5.1
Supervisor: 2024.04.4
Operating System: 12.2
Frontend: 20240501.0

Installing and loading as in read me, but no entity's are shown up after restarting HA.
tried multiple configurations, and reinstallations all no succes.

Please check

**Comment by m4recek** [comment]
Same here, I created a working setup with Rpi4 about two weeks ago. I think I repeated all the steps yesterday on Rpi5 but no entity is showing up (I've only got switches).

Core: 2024.5.1
Supervisor: 2024.04.4
Operating System: 12.2
Frontend: 20240501.0
HACS: 1.34.0
RpiGPIO: 2022.7.0

Configuration.yaml
<img width="933" alt="Screenshot 2024-05-06 at 19 08 10" src="https://github.com/thecode/ha-rpi_gpio/assets/1221226/cd45ec15-7aa3-46f6-b84e-32b529e2461c">

**Comment by thecode** [comment]
https://github.com/thecode/ha-rpi_gpio/issues/246#issuecomment-2041456367

**Comment by thecode** [comment]
https://github.com/thecode/ha-rpi_gpio/issues/255#issuecomment-2103366690
