### ISSUE TITLE
Binary sensor issue

### ISSUE THREAD

**Issue by stegno** [thecode/ha-rpi_gpio#275]
### Hello guys. Unfortunately I can't setup binary sensor. But Cover and Switch entities work well..

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:364
integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 10:20:02 PM (1 occurrences)
Last logged: 10:20:02 PM

```
Error while setting up rpi_gpio platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio/binary_sensor.py", line 77, in setup_platform
    RPiGPIOBinarySensor(
  File "/config/custom_components/rpi_gpio/binary_sensor.py", line 132, in __init__
    edge_detect(self._port, edge_detected, self._bouncetime)
  File "/config/custom_components/rpi_gpio/__init__.py", line 59, in edge_detect
    GPIO.add_event_detect(port, GPIO.BOTH, callback=event_callback, bouncetime=bounce)
RuntimeError: Failed to add edge detection
```

**Comment by soundstorm** [comment]
The dependency in the manifest is RPi.GPIO=0.7.1, as of bookworm the API changed and we'd need rpi-lgpio instead. I don't know if @thecode is still maintaining this, otherwise we may need a fork with lgpio for newer OS.

**Comment by soundstorm** [comment]
Already done: https://github.com/thecode/ha-rpi_gpio/issues/255#issuecomment-2103366690

**Comment by soundstorm** [comment]
Even though the Library itself is a drop in replacement.

**Comment by stegno** [comment]
> Even though the Library itself is a drop in replacement.

So, what should we do? Integration is still not working...

**Comment by Otiel** [comment]
@stegno Use https://github.com/jdeneef/ha_gpiod instead of https://github.com/thecode/ha-rpi_gpio

**Comment by thecode** [comment]
> The dependency in the manifest is RPi.GPIO=0.7.1, as of bookworm the API changed and we'd need rpi-lgpio instead. I don't know if @thecode is still maintaining this, otherwise we may need a fork with lgpio for newer OS.

I don't have a PI hardware available to do the migration and testing, however I am accepting PRs so anyone who wants to do the migration is welcome.

**Comment by soundstorm** [comment]
rpi-lgpio provides the same API as RPi.GPIO - neither the imports nor the method calls are different, so really a manifest change to rpi-lgpio should do it.
I was just changing the requirements.txt all my projects without touching the code :)
