### ISSUE TITLE
Not working on HA 2024.10.1

### ISSUE THREAD

**Issue by gvamporov** [thecode/ha-rpi_gpio#294]
Hello.
Since i updated to HA 2024.10.1 (currently on 2024.10.3)  this integration does not work anymore. I get this when i do "Check configuration":

> Platform error 'binary_sensor' from integration 'rpi_gpio' - No module named 'RPi._GPIO'

Is there a fix for this?
What information is needed to help resolve the issue?
Thanks in advance.

**Comment by il77781** [comment]
It's the same for me... Is there any solution?

**Comment by thecode** [comment]
You probably updated the OS together, see https://github.com/thecode/ha-rpi_gpio/issues/255 
The library is not supported anymore by newer kernels, there is WIP to switch to a newer library, I don't have a timeline.

**Comment by il77781** [comment]
Yes, I have upgraded to BookWorm... Prior to that, simply updating HA (without updating to BookWorm) did not lead to such results...
It remains to wait for you to figure it out.: https://github.com/thecode/ha-rpi_gpio/discussions/285 ?

**Comment by gvamporov** [comment]
> You probably updated the OS together, see #255 The library is not supported anymore by newer kernels, there is WIP to switch to a newer library, I don't have a timeline.

In my case, I'm using Home Assistant on docker container, so i don't think it is OS related... The issue appeared after upgrading the HA container to 2024.10.1. 
On different device I have HA container still on 2024.9.3 and the integration works fine...

**Comment by il77781** [comment]
> In my case, I'm using Home Assistant on docker container, so i don't think it is OS related... The issue appeared after upgrading the HA container to 2024.10.1.

In my case, I use HA Supervised. As far as I understand, it is also installed in a container... I upgraded to BookWorm after the supervisor started "swearing" at the outdated version... And after that, the integration stopped working...
In addition, there is such information: https://github.com/thecode/ha-rpi_gpio/discussions/284#discussioncomment-11010333

**Comment by thecode** [comment]
Fixed in https://github.com/thecode/ha-rpi_gpio/releases/tag/2024.10.0
