### ISSUE TITLE
Invalid config for 'switch'

### ISSUE THREAD

**Issue by alexdurdan** [thecode/ha-rpi_gpio#307]
Invalid config for 'switch' from integration 'rpi_gpio' at configuration.yaml, line 29: 'ports' is an invalid option for 'rpi_gpio.switch', check: ports, please check the docs at https://github.com/thecode/ha-rpi_gpio

I have tried to modify the configuration but nothing works... I will share my configuration here maybe someone can help if is not an issue.

# Raspberry Pi Cooling Fan
sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"
    scan_interval: 10

switch:
  - platform: rpi_gpio
    ports:
      15: RPI Cooling Fan

climate:
  - platform: generic_thermostat
    name: RPI Cooling Fan Controller
    heater: switch.rpi_cooling_fan
    target_sensor: sensor.cpu_temperature
    min_temp: 50
    max_temp: 80
    ac_mode: true
    target_temp: 70
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 5
    initial_hvac_mode: "cool"

Best regards,
Alex

**Comment by xifias21** [comment]
Hi Alex , 
I have the same issue but I haven't found the solution yet . 

BR
Christos

**Comment by xifias21** [comment]
Hi pjurewicz, 

Thanks a lot 
I solve my issue like this

**Comment by aldurdan** [comment]
> Hey @alexdurdan, try chnaging your seetings from:
> 
> ```
> - platform: rpi_gpio
>     ports:
>     15: RPI Cooling Fan
> ```
> 
> to:
> 
> ```
> - platform: rpi_gpio
>     switches:
>        - port: 15
>          name: RPI Cooling Fan
> ```

I have tried but does not work… i had to restore my backup… I saw this issue was closed but I still believe is a bug…
