### ISSUE TITLE
update 2022.2.3 to 2022.3.0 not updated after reboot

### ISSUE THREAD

**Issue by f3bandit** [thecode/ha-rpi_gpio#32]
When I update from 2022.2.3 to 2022.3.0, and the download and install completes. Home Assist. directs me to restart.
Once the restart completes, Home Assist states the same version update is available for download and install.

**Comment by thecode** [comment]
The update process is not related to the integration, I don't know how you download and update (HACS or other option), I  suggest to try to update again and if it still doesn't work check the logs for errors

**Comment by f3bandit** [comment]
No idea why this keeps happening!?! Raspberry Pi 4 8GB 
Hard wired to lan thru ethernet.
This is the log it generates before doing a restart.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:870
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 10:04:32 AM (2 occurrences)
Last logged: 10:04:32 AM

[switch.py] was not downloaded.
[services.yaml] was not downloaded.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:597
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 10:04:32 AM (2 occurrences)
Last logged: 10:04:32 AM

A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/thecode/ha-rpi_gpio/2022.3.0/custom_components/rpi_gpio/switch.py, check the network on the host running Home Assistant
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/thecode/ha-rpi_gpio/2022.3.0/custom_components/rpi_gpio/services.yaml, check the network on the host running Home Assistant

**Comment by thecode** [comment]
```
A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/thecode/ha-rpi_gpio/2022.3.0/custom_components/rpi_gpio/switch.py, check the network on the host running Home Assistant
```
Something preventing your from reaching GitHub, try to click on the link in the browser and see if it opens, if it is not the issue is within your Network/ISP or GitHub. If it does open there is some issue with your home assistant, you can try to reboot it.

**Comment by fraygon** [comment]
Same problem. The HA log shows no errors. I keep trying to update but once I restart HA (even turning off everything) the update request always comes back.

**Comment by thecode** [comment]
> Same problem. The HA log shows no errors. I keep trying to update but once I restart HA (even turning off everything) the update request always comes back.

It is not the same problem if you don't see anything in the log, because the log added by @f3bandit shows there is timeout fetching the files from GitHub. 

Note that  as I already explained above the update process is not related to the integration. The integration is just files, it doesn't know to update itself, updates are either done manually by coping files or via HACS which both are not controlled by something in this integration.
