### ISSUE TITLE
Can't get gpio switches set to 1

### ISSUE THREAD

**Issue by Toug19** [thecode/ha-rpi_gpio#320]
Hi,
In fact I can't get the ha-rpi_gpio module to work.
I tried 3 gpio and never measured active state when setting state to 1 in entity HA settings.

Here is what I did:
I went to HACS, installed ha-rpi_gpio module.
Make a full HA restart
Modified configuration.yaml, with this settings (to be viewed as code to avoid md formatting)

rpi_gpio:
  path: '/dev/gpiochip0'

switch:
  - platform: rpi_gpio
    switches:
      - port: 21
        name: "Chaudiere_gpio21_pin40"
        unique_id: "chaudiere_gpio21_pin40"
      - port: 16
        name: "Plancher_gpio16_pin36"
        unique_id: "plancher_gpio16_pin36"
      - port: 20
        name: "ECS_gpio20_pin38"
        unique_id: "ecs_gpio20_pin38"

I made a new full restart.

I went to entities, found the 3 switches:
![image](https://github.com/user-attachments/assets/c695ecdd-87e5-41fa-b8b3-6f1fe683c8be)
Activated them,
but still 0V on the 3 gpios.

Did I forgot something?

**Comment by tomer-w** [comment]
What raspberry pi do you use?
Can we get logs?

**Comment by pppATH0** [comment]
I am not the OP of this issue, but I'm having the same issue.   I am running this on a raspberry pi 4 (rpi4-64).  My switch configuration is below:
   
switch:
  platform: rpi_gpio
  switches:
    - port: 22
      name: "light_button_dog_fed"

And I see nothing in the logs regarding this integration.  If you point me in the right direction, I can post whichever log you would need.  I have the integration set to debug logging right now.

I can change the invert_logic flag and it will change the state of the output, but changing the state of the switch will not have any effect on either state of the invert_logic flag.

Up until the last update today, my cover was able to control the outputs and open and close my garage door.  Today, the cover is not longer available, but I cannot seem to find any errors in the logs for that either.  Maybe I'm looking in the wrong place.

This configuration worked previously on my pi3 (which met an untimely end recently).  

Please let me know what I can do to help out here.  Sorry if I'm short on details, be gentle, I'll get what you need.

**Comment by pppATH0** [comment]
Sorry, did a little digging and found what you are looking for in the way of the logs, I hope.  Please find the most recent logs with debugging enabled attached.

[home-assistant_2024-12-03T01-22-43.668Z.log](https://github.com/user-attachments/files/17985848/home-assistant_2024-12-03T01-22-43.668Z.log)

**Comment by Toug19** [comment]
I use à raspberry pi 4.
Here are the HA logs, didn't see something revelant:
[home-assistant_2024-12-03T20-19-18.340Z.log](https://github.com/user-attachments/files/17998564/home-assistant_2024-12-03T20-19-18.340Z.log)

**Comment by tomer-w** [comment]
Hi @Toug19 , I dont see the relevant log lines. I assume you didnt follow the instructions defined [here](https://github.com/thecode/ha-rpi_gpio?tab=readme-ov-file#reporting-issues). 
You should see way more lines with the ```rpi_gpio``` prefix. When you have it, I will take a look again.

**Comment by Toug19** [comment]
Isn't it activated?
![image](https://github.com/user-attachments/assets/31bcf108-27dd-4728-a814-de92ee4a615b)
Translating to "debug activated" which is maybe not the exact message that would appear on a english HA.
Then I reboot.
The logs I provide comes from settings->system->Logs.

**Comment by Toug19** [comment]
Here are more logs, in this one, I see theses lines:
[home-assistant_2024-12-04T12-10-02.978Z.log](https://github.com/user-attachments/files/18007880/home-assistant_2024-12-04T12-10-02.978Z.log)

> We found a custom integration rpi_gpio which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-03 21:17:09.156 DEBUG (MainThread) [custom_components.rpi_gpio.hub] in turn_on 20

**Comment by tomer-w** [comment]
The logs seems to include references for ```pigpio```. Not an expert but it might be conflicting with this library. Do you know why it is loaded? Can you remove that?
Also, the logs are still missing lot of relevant logs lines. Not sure how you got to that situation.

**Comment by tomer-w** [comment]
Maybe you didnt restart after enabling the traces?
You should see something like the following line when tracing is enabled:
```
2024-12-04 23:20:32.926 DEBUG (MainThread) [custom_components.gpiod] rpi_gpio integration starting. Version: 2024.11.0
```

**Comment by Toug19** [comment]
I did a lot of restart since enabling the logs because I made some new installation.
Anyway, I uninstalled the rpi_gpio integration through HACS, updated the system, installed again rpi_gpio and made a new check on gpio 21. And it is now working! I also noticed that the logs are present.

**Comment by tomer-w** [comment]
Bummer that we dont have the root cause of what happened here but I'm happy to hear it got resolved!!
