### ISSUE TITLE
Cover fails to load after latest update (errors in hub.py)

### ISSUE THREAD

**Issue by pppATH0** [thecode/ha-rpi_gpio#326]
After upgrading rpi_gpio tonight, my cover which previously worked is not reported as not being provided anymore.  The following log entry is seen in the Home Assistant Core logs.

Log details (ERROR)
Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:599
integration: Cover ([documentation](https://www.home-assistant.io/integrations/cover), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cover%22))
First occurred: 7:38:26 PM (1 occurrences)
Last logged: 7:38:26 PM

Error adding entity cover.joe_garage_door for domain cover with platform rpi_gpio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1367, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/rpi_gpio/cover.py", line 112, in async_added_to_hass
    self._hub.add_cover(self, self._relay_port, self._relay_active_low, self._relay_bias,
  File "/config/custom_components/rpi_gpio/hub.py", line 214, in add_cover
    self.add_sensor(entity, state_port, state_active_low, state_bias, 50)
  File "/config/custom_components/rpi_gpio/hub.py", line 204, in add_sensor
    _LOGGER.debug(f"current value for port {port}: {entity.is_on}")
                                                    ^^^^^^^^^^^^
AttributeError: 'GPIODCover' object has no attribute 'is_on'. Did you mean: 'icon'?

Config.yaml definition.

      
cover:
  platform: rpi_gpio
  relay_time: 1
  invert_relay: false
  invert_state: false
  state_pull_mode: 'DOWN'
  covers:
  - relay_pin: 17
    state_pin: 27
    name: 'Joe Garage Door'

Running on a raspberry pi 4.

I see there was recent commits in that area of the hub.py file, but I am not able to help any further there.  Please let me know if I can provide anything else for testing.

Joe

**Comment by pppATH0** [comment]
On my local machine, I changed hub.py line 202 from entity._attr_is_on to just entity.is_on and the cover loads again.  I don't know what other knock on effects that may have, I'll leave that to the experts, but I'll test whatever needs testing.

**Comment by tomer-w** [comment]
Sorry about this regression. Will fix in the next hour. Meanwhile you can revert to previous version.

**Comment by pppATH0** [comment]
It's all good, we're only human.  I'm currently stable with my manual edits.  I look forward to the official push.

--Joe

**Comment by tomer-w** [comment]
Your fix is the correct one. I will do that and add some comment to never try that change again :(.

**Comment by pppATH0** [comment]
Bah, you just missed changing the line to match what is being used elsewhere in the code. Thank you for your work on this.  We all appreciate you working to maintain this integration. 

Cheers!

**Comment by tomer-w** [comment]
Release [2024.12.1](https://github.com/thecode/ha-rpi_gpio/releases/tag/2024.12.1) published. It should work. Reopen the issue if any issue arises.
