### ISSUE TITLE
Cover initialization issue

### ISSUE THREAD

**Issue by willisk0612** [thecode/ha-rpi_gpio#333]
Each time i restart HA the rpi_gpio cover state changes to "unavailable". It updates correctly when i physically change the sensor state. Running HA Core 2024.12.4 on Supervisor 2024.12.0.

**Comment by willisk0612** [comment]
I also experienced the same issue using a binary sensor. Could it be that self._attr_is_closed = self._hub.get_line_value(self._state_port) must be added after line 113 in cover.py so the state gets updated on initialization in addition to a GPIO event?

**Comment by tomer-w** [comment]
What version of the integration are you using? I would suspect you are not using the latest version.
Can you share the integration log from the startup sequence?

**Comment by willisk0612** [comment]
@tomer-w I am using version 2024.12.1 which is the latest on github. Here is the log:
[halog.log](https://github.com/user-attachments/files/18262112/halog.log)

**Comment by tomer-w** [comment]
@willisk0612 , I just published new version that improve the detection of the cover after restart. Can you check it out? If this is not solving your problem, it will be great to have new logs and description of the actual cover state in each time frame.

**Comment by willisk0612** [comment]
@tomer-w The new version fixed the issue 👍

**Comment by tomer-w** [comment]
Happy to hear!!
