### ISSUE TITLE
Documentation clarifications

### ISSUE THREAD

**Issue by fangly** [thecode/ha-rpi_gpio#34]
I am new to Home Assistant and to using the Raspberry Pi's GPIO system. I am trying to operate some Somfy blinds from within Home Assistant.

In rpi_gpio, platform types are `binary_sensor`, `cover` and `switch`. While `binary_sensor` is explained pretty clearly in the documentation, the purpose of `cover` and `switch` could be better explained.

**switch:** Is `switch` supposed to emulate a physical switch, i.e. a button with two positions, which once pressed stays in its current state? Example: a switch for a light.

**cover:** Is `cover` supposed to emulate a push button, by that I mean a button which you push once to open something and once again to close In that case, I find the name `cover` misleading since it is too restrictive. Further to that, the `state_pin` is required. But what to do if there is no sensor for the state (like in my case)? Is this platform then useless or can I specify a dummy `state_pin`?

**Comment by thecode** [comment]
Hi,
First if you are new to Home Assistant and does not already have legacy hardware connected to GPIOs that you can't use with another solution I highly suggest not to start with it. This repository is mainly to provide backward compatible solution for users who are already using it.

The names for the platforms here are Home Assistant platforms, This integration is representing 3 types of Home Assistant platforms `binary_sensor`, `switch` and `cover` as GPIOs based devices.

You can read about them in Home Assistant documentation:
https://www.home-assistant.io/integrations/binary_sensor/
https://www.home-assistant.io/integrations/switch/
https://www.home-assistant.io/integrations/cover/

Note that GitHub issues are used to track bugs and not for providing support, If you are in need of support I highly recommend to try Home Assistant [Community Forum](https://community.home-assistant.io) or [Discord chat server](https://discord.gg/c5DvZ4e). I will be also glad to answer questions on Discord and help you progress in getting to know how Home Assistant works.

Thanks! 👍
