### ISSUE TITLE
MHZ19

### ISSUE THREAD

**Issue by bombaata** [thecode/ha-rpi_gpio#35]
Hi, I'm using a MH-Z19 CO2 and Temperature Sensor with Raspberry Pi GPIO UART (/dev/ttyS0). Works perfectly on current Hassio (2022.3.6) integration.

Does this custom integration support this sensor ? Can't find how to configure it to get its values.

**Comment by thecode** [comment]
You are referring to: https://www.home-assistant.io/integrations/mhz19
I am only maintaining the GPIO integration: https://www.home-assistant.io/integrations/rpi_gpio/ which is another integration, not the one you are using. You will have to wait for a developer to pick it up.
