### ISSUE TITLE
How to get bme280 working with this?

### ISSUE THREAD

**Issue by kevinkey619** [thecode/ha-rpi_gpio#58]
Hi,

I have a bme280 connected to my Raspberry Pi 4 pins SDA and SCL. I had it working as in integration with earlier versions of HA. 

What should my configuration.yaml entry look like for this?

**Comment by thecode** [comment]
This is integration is only for GPIO (as documented), I don't know about BME280, it is a different integration (if exists)

**Comment by kevinkey619** [comment]
Okay. Thanks anyway.
