### ISSUE TITLE
1-wire with SysBus support

### ISSUE THREAD

**Issue by Misiu** [thecode/ha-rpi_gpio#60]
@thecode sorry for writing here, but I didn't find a better way.
As you probably know in HA 2022.6 GPIO support will be removed, and with it also 1-Wire SysBus will be gone (https://github.com/home-assistant/core/pull/71232).
You did an awesome job by maintaining this repository and many (including me) are very grateful for that.
Do you use 1-Wire sensors in your setup? I have a homemade floor heating system that is controlled by 1-wire sensors, so I must stay with HA 2022.5.x.
maybe you could recommend other solution or maybe create a fork as you did with rpi_gpio.

Do you have a [buy-me-a-coffee](https://www.buymeacoffee.com/) account or patreon? Many users would like to thank you not just by words :)

**Comment by thecode** [comment]
I don't use 1-wire directly in my setup (use it via ESP8266), however I have 1-wire sensors, I am considering adding support for this.

**Comment by Misiu** [comment]
@thecode awesome news. Maybe consider adding a new repository, similar to this one.
I'm looking forward to this and I'm willing to help with testing and as much as I can with the development.
Do you think that this should be 1-wire integration that is available in 2022.5.5 but with removed everything except SysBus?

**Comment by thecode** [comment]
> is available in 2022.5.5 but with removed everything except SysBus?

Yes

**Comment by thecode** [comment]
Initial version https://github.com/thecode/ha-onewire-sysbus
Not tested on real hardware yet, if you can test please test, if you find something please create an issue on the ha-onewire-sysbus repo.
Thanks.

**Comment by Misiu** [comment]
Thank you! I will test this as soon as I create dev env.

P.S. please remember about buymeacoffee account ;)

**Comment by thecode** [comment]
@Misiu Did you had time to test it?
