### ISSUE TITLE
GPIO based switch skipps second GPIO

### ISSUE THREAD

**Issue by ShivaSVK** [thecode/ha-rpi_gpio#69]
I have a Raspberry Pi 4 running Home Assistant. I have been using it for automation of my covers using two relays:
Relay 1: NC: disconnect manual wall switch
             NO: power to Relay 2
Relay 2: NC: travel UP
             NO: travel DOWN
Relays are connected to 3v3 to 24V converter which powers the relays.
So if I want the covers to move up, I just switch on Relay 1 (using a GPIO). If I want to close the covers, I need to switch both relays at once. This was working well with the below code till the migration to rpi_gpio using the below code:

`switch:
  - platform: rpi_gpio
    ports:
      6:  Žalúzie 1 # Detská pravá
      13: Žalúzie 2 # 
  - platform: template
    switches:
      detska_p_zaluzie_hore: #UP
        turn_on:
          - service: switch.turn_off
            target:
              entity_id: switch.zaluzie_2
          - service: switch.turn_on
            target:
              entity_id: switch.zaluzie_1
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.zaluzie_1
          - service: switch.turn_off
            target:
              entity_id: switch.zaluzie_2
      detska_p_zaluzie_dole: #DOWN
        turn_on:
          - service: switch.turn_on
            target:
              entity_id: switch.zaluzie_1
          - service: switch.turn_on
            target:
              entity_id: switch.zaluzie_2
        turn_off:
          - service: switch.turn_off
            target:
              entity_id: switch.zaluzie_1
          - service: switch.turn_off
            target:
              entity_id: switch.zaluzie_2

cover:
  - platform: cover_time_based_synced
    devices:
      zaluzie_detska_l_ovladanie:
        name: Žalúzie detská ľavá
        travelling_time_up: 38
        travelling_time_down: 38
        close_switch_entity_id: switch.detska_l_zaluzie_dole
        open_switch_entity_id: switch.detska_l_zaluzie_hore
        send_stop_at_ends: True #optional
        aliases: #optional
          - zaluzie_detska_l_time_based`

Now, the travel DOWN sometimes does not work. The automation or cover switch in HA to move down only turns on Relay 1 and the covers are opening instead of closing. I use it for 8 windows and every day it randomly skips some of the covers. Also pressing the down arrow in HA sometimes works well and sometimes not. So it randomly skipps the second service in my switch.

**Comment by thecode** [comment]
The integration is almost an exact copy of the `rpi_gpio` taken from Home Assistant `2022.2.0` so unless you were using an older version of the `rpi_gpio` there are no changes. I have looked over the code that is related to the Switch component and there are no changes on the control there.
However your cover is based on few components which are not related to this integration and I have no control of, the template which had many changes and the `cover_time_based_synced` which I have no idea what is it.

If you want to move forward with this please debug the switch control as a standalone. You only use two switches so it should be easy to debug. You can also downgrade to version 2022.2.0 of this integration which is 100% the copy of the last version from Home Assistant.
