### ISSUE TITLE
Problem since upgrading to 2022.6.7

### ISSUE THREAD

**Issue by alastaid** [thecode/ha-rpi_gpio#73]
I use a devops pipeline for my HA yaml changes, and part of the pipeline executes a "ha core check" before restarting HA. I am pretty sure as I have upgraded to 2022.6.7 my pipelines fail at "ha core check" with the following:

pi@bhha:~/myagent/_work/_temp $ ha core check
Error: Testing configuration at /config
INFO:homeassistant.util.package:Attempting install of spotify_token==1.0.0
INFO:homeassistant.util.package:Attempting install of RPi.GPIO==0.7.1a4
ERROR:homeassistant.util.package:Unable to install package RPi.GPIO==0.7.1a4: error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-310
      creating build/lib.linux-armv7l-cpython-310/RPi
      copying RPi/__init__.py -> build/lib.linux-armv7l-cpython-310/RPi
      creating build/lib.linux-armv7l-cpython-310/RPi/GPIO
      copying RPi/GPIO/__init__.py -> build/lib.linux-armv7l-cpython-310/RPi/GPIO
      running build_ext
      building 'RPi._GPIO' extension
      creating build/temp.linux-armv7l-cpython-310
      creating build/temp.linux-armv7l-cpython-310/source
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.10 -c source/c_gpio.c -o build/temp.linux-armv7l-cpython-310/source/c_gpio.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

** loads of similar errors after this all related to 'gcc' failed

Its possible I havent run the pipeline before the upgrade and the error may have come before 2022.6.7.  The rpi.gpio covers I have still work in HA, so not sure if this error is to do with HA, rpi.gpio or my specific setup, if you could give me some pointers to look for?

Thanks, Alastair

**Comment by thecode** [comment]
Can you add information about what type of installation you are using? What was the last working version?

**Comment by thecode** [comment]
By hassio you mean Home Assistant Supervised? can you link to the installation method you are using?
If you are using Supervised or core container installation types this wheel is included in the image, otherwise you need to build it yourself.
Note that there are no changes related to this in HA core and there was no release for this integration since 2022.6.0

**Comment by alastaid** [comment]
Firstly thanks for supporting me on this, very much appreciated. So yes my installation is Home Assistant Supervised, so basically install OS, then install Docker, then install Home Assistant Supervised and I also run a bunch of other containers.  This setup has been working for years, (the running ha core check in my pipeline), and I switched over to HACS rpi_gpio quite early on after the deprecation notice, and it has run fine. I read the release notes, and I am stumped as to why this would do this now as nothing seems to have changed.  Can you repro this?  If you run ha core check on a Supervised instance of 2022.6.7 does it work fine?  Would you expect it to force a recompile on an ha core check?  It looks like gcc is either not there or not available in the container which  is why it is failing, any ideas of where I could start looking to fix?  Thanks again.

**Comment by thecode** [comment]
I have tested today both updating from previous version and reinstall on `2022.6.7` and could not reproduce this error.
Does your system has access to the internet? That is the only thing I can think of.
Anyhow from `2022.7.x` the wheel building system in Home Assistant is changed so it would be good if you test it again after it is released.

**Comment by alastaid** [comment]
Thanks for trying to repo, considering I am the only reporting it, it must be specific to my system, I have found a different way in the pipeline by issuing the following instead of the ha core check: 'docker exec homeassistant python -m homeassistant --config /config --script check_config | ( ! grep ERROR )'  which works and passes if the yaml is correct.  I will try 2022.7.x when its released and report back for info (if useful), and then this can get closed off.

**Comment by alastaid** [comment]
Just upgraded to 2022.7 and its still the same, so going to close this as it must be related to my install,  thanks for the support.

**Comment by thecode** [comment]
Did you also update the integration?

**Comment by alastaid** [comment]
No I didn't. just done that and it is fixed! So thanks again
