### ISSUE TITLE
Can't install on beta via hacs

### ISSUE THREAD

**Issue by RubenKelevra** [thecode/ha-rpi_gpio#78]
![Screenshot_2022-06-30-13-48-48-605_io.homeassistant.companion.android.jpg.png](https://user-images.githubusercontent.com/614929/176670526-4c6afb68-bb8f-4af6-9868-35f03517e095.png)

**Comment by thecode** [comment]
In `2022.7.0` the wheel building system is changed. I preferred not to release an intermediate version, which might not be a good decision.
Anyhow core `2022.7.0` will be released in few days, in the meantime you can update the following file on your existing installation which will make it work on the beta series for 2022.7.
https://github.com/thecode/ha-rpi_gpio/blob/main/custom_components/rpi_gpio/manifest.json
When `2022.7.0` will be released HACS will offer an update as usual.
