### ISSUE TITLE
walking in the dark  -  literally

### ISSUE THREAD

**Issue by eugeniostreliaev** [thecode/ha-rpi_gpio#79]
Hi, any help will bem greatly appreciated, because I am actually in a dark home using flashlights to see at night. All my lighting is controlled by 32 relays through rasp gpios.
I am running a rasp 3 64 bit, Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3,
Home Assistant OS 8.2

I have both tried HACS and also have manually created the custom_components and rpi_gpio folders and placed rpi_gpio contents on it with no success.

> 2022-07-01 21:12:37 ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package RPi.GPIO==0.7.1: error: subprocess-exited-with-error
> × python setup.py bdist_wheel did not run successfully.
> │ exit code: 1
> ╰─> [15 lines of output]
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build/lib.linux-aarch64-cpython-39
> creating build/lib.linux-aarch64-cpython-39/RPi
> copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-39/RPi
> creating build/lib.linux-aarch64-cpython-39/RPi/GPIO
> copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-39/RPi/GPIO
> running build_ext
> building 'RPi._GPIO' extension
> creating build/temp.linux-aarch64-cpython-39
> creating build/temp.linux-aarch64-cpython-39/source
> gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.9 -c source/c_gpio.c -o build/temp.linux-aarch64-cpython-39/source/c_gpio.o
> error: command 'gcc' failed: No such file or directory
> [end of output]
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ERROR: Failed building wheel for RPi.GPIO
> error: subprocess-exited-with-error
> × Running setup.py install for RPi.GPIO did not run successfully.
> │ exit code: 1
> ╰─> [17 lines of output]
> running install
> /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
> warnings.warn(
> running build
> running build_py
> creating build
> creating build/lib.linux-aarch64-cpython-39
> creating build/lib.linux-aarch64-cpython-39/RPi
> copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-39/RPi
> creating build/lib.linux-aarch64-cpython-39/RPi/GPIO
> copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-39/RPi/GPIO
> running build_ext
> building 'RPi._GPIO' extension
> creating build/temp.linux-aarch64-cpython-39
> creating build/temp.linux-aarch64-cpython-39/source
> gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.9 -c source/c_gpio.c -o build/temp.linux-aarch64-cpython-39/source/c_gpio.o
> error: command 'gcc' failed: No such file or directory
> [end of output]
> note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> × Encountered error while trying to install package.
> ╰─> RPi.GPIO
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.
>

**Comment by thecode** [comment]
The version you are trying to install (probably manually) is not compatible with core 2022.6.7.
Please use the following:
https://github.com/thecode/ha-rpi_gpio/tree/2022.6.0

**Comment by eugeniostreliaev** [comment]
Thank you ever so much for the reply. This is certaily the reason. Thanks. :-)
YOU SAVED MY LIFE. (and my marriage)
I works, I have light

**Comment by thecode** [comment]
Closing this issue feel free to reopen if it happens again.
For `2022.7.0` I suggest to wait for final release (skip the betas) due to changes in the wheel system. Make a backup before update so if you have issues you can go back.

**Comment by eugeniostreliaev** [comment]
ok! and thanks again! 👍 💯
