### ISSUE TITLE
Syntax errors when trying a HA restart after adjusting configuration.yaml after installing rpi_gpio from HACS

### ISSUE THREAD

**Issue by reidje** [thecode/ha-rpi_gpio#80]
Hi, first a big thank you for keeping rpi_gpio up and running. I never understood the reason for removal from HA.

I'm using the Supervised version of HA. After installing from HACS the 6 version, I adjusted the description for the switch and binary_sensor in my configuration.yaml just the way you wrote it in the readme file. But when I tried to restart HA, I got errors on the syntax of the just entered lines. When I leave the description of the switch and binary_sensor  unaltered, HA restarts without any problem. The automations that use rpi_gpio work just fine, so the installation seams succesfull. 

All-in all there seams to be no need for adjusting the configuration.yaml after installing.

**Comment by thecode** [comment]
That is correct, there is no need to adjust the configuration if you already have a working one.
However I was asked to add option for adding unique id which required a new configuration scheme, so both configurations are supported and I recommend for new users to start with the new one.
