### ISSUE TITLE
Requirements for rpi_gpio not found: ['RPi.GPIO==0.7.1']

### ISSUE THREAD

**Issue by ScratMan** [thecode/ha-rpi_gpio#84]
I have installation issues with 2022.7.0 of HA running in a docker container.
I followed the recommendations given in the (identical but closed) issue #83, I tried to remove rpi_gpio from my config, uninstall integration, restart HA, install integration, restart HA, and everything is fine in the log. But as soon I add the rpi_gpio integration config in the yaml, I get the installation error in the log during the config check : 
`Platform error switch.rpi_gpio - Requirements for rpi_gpio not found: ['RPi.GPIO==0.7.1'].`

And more detail in the container's log :
```
2022-07-07 11:59:56 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package RPi.GPIO==0.7.1: error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-310
      creating build/lib.linux-armv7l-cpython-310/RPi
      copying RPi/__init__.py -> build/lib.linux-armv7l-cpython-310/RPi
      creating build/lib.linux-armv7l-cpython-310/RPi/GPIO
      copying RPi/GPIO/__init__.py -> build/lib.linux-armv7l-cpython-310/RPi/GPIO
      running build_ext
      building 'RPi._GPIO' extension
      creating build/temp.linux-armv7l-cpython-310
      creating build/temp.linux-armv7l-cpython-310/source
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for RPi.GPIO
  error: subprocess-exited-with-error
  × Running setup.py install for RPi.GPIO did not run successfully.
  ╰─> [17 lines of output]
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> RPi.GPIO
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

The YAML looks like this : 
```
- platform: rpi_gpio
  switches:
    - port: 5
      name: "Volet Cuisine Montée"
      invert_logic: true
    - port: 6
      name: "Volet Cuisine Descente"
      invert_logic: true
    - port: 13
      name: "Volet Baie Sud-Est Montée"
      invert_logic: true
    - port: 16
      name: "Volet Baie Sud-Est Descente"
      invert_logic: true
    - port: 19
      name: "Volet Baie Sud-Ouest Montée"
      invert_logic: true
    - port: 20
      name: "Volet Baie Sud-Ouest Descente"
      invert_logic: true
    - port: 21
      name: "Volet Bureau Montée"
      invert_logic: true
    - port: 26
      name: "Volet Bureau Descente"
      invert_logic: true

```

**Comment by thecode** [comment]
Can you link to the container you are using? Home Assistant core container should not need this package

**Comment by ScratMan** [comment]
Using homeassistant/home-assistant:stable sha256:c2ce05132aa81b4da7bbfff79eb8e82ad7baffd18f4f4b5d9be29e3670517837
https://hub.docker.com/r/homeassistant/home-assistant

**Comment by ScratMan** [comment]
Gère it is.

![Screenshot_20220707-201432](https://user-images.githubusercontent.com/971926/177841612-679efbb2-7ab2-4a60-a42a-b93e1b10d50a.png)

**Comment by ScratMan** [comment]
> Delete the Rpi GPIO configuration (configuration.yaml). Update Rpi GPIO version 2022.7.0. Restart HA. After reboot, insert Rpi Gpio configuration and restart HA again.

Already done, not working.

**Comment by thecode** [comment]
> > Delete the Rpi GPIO configuration (configuration.yaml). Update Rpi GPIO version 2022.7.0. Restart HA. After reboot, insert Rpi Gpio configuration and restart HA again.
> 
> Already done, not working.

The above should work. Your system should be supported and the wheel should be downloaded from https://wheels.home-assistant.io/musllinux/RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl automatically on new install. 

You can try:
1. Repeat the suggestion above again. Maybe remove the `rpi_gpio` completely, restart HA, do fresh install from HACS and add the configuration back.
2. Download the wheel from the link above and manually install it: `pip install RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl`

**Comment by ScratMan** [comment]
> > > Delete the Rpi GPIO configuration (configuration.yaml). Update Rpi GPIO version 2022.7.0. Restart HA. After reboot, insert Rpi Gpio configuration and restart HA again.
> > 
> > 
> > Already done, not working.
> 
> The above should work. Your system should be supported and the wheel should be downloaded from https://wheels.home-assistant.io/musllinux/RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl automatically on new install.
> 
> You can try:
> 
> 1. Repeat the suggestion above again. Maybe remove the `rpi_gpio` completely, restart HA, do fresh install from HACS and add the configuration back.
> 2. Download the wheel from the link above and manually install it: `pip install RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl`

Thanks, I could fix the issue.
Didn't use the step 1 (I did it several times unsuccessfully), so I had the error at container boot and config check.

So I first connected to the container's console as root, then I used the `wget https://wheels.home-assistant.io/musllinux/RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl` command to download the wheel.
After that your step 2 worked to install the missing dependency, and I could then check the config successfully and restart Home Assistant without issue, now rpi_gpio works perfectly.

But I really don't understand why the wheel installation could work with manual method and not when using HACS.

**Comment by ScratMan** [comment]
The issue came back after updating the HA docker container to 2022.7.2

**Comment by ScratMan** [comment]
The issue came back after updating the HA docker container to 2022.7.2

**Comment by thecode** [comment]
I guessed the issue will come back for you, for some reason your system is not pulling the wheel from Home Assistant, on another PR someone suggested to reboot the host (not only core), can you try it?

**Comment by bepece1** [comment]
ha-rpi_gpio (v.2022.6.0) works but v.2022.7.0 no works, what's happens?
Testing in homeassistant docker (2022.6.7 and 2022.7.0)

**Comment by thecode** [comment]
@bepece1 please create a separate issue

**Comment by ScratMan** [comment]
> I guessed the issue will come back for you, for some reason your system is not pulling the wheel from Home Assistant, on another PR someone suggested to reboot the host (not only core), can you try it?

I'll try on the next update.

**Comment by ScratMan** [comment]
Today I tried to reboot the Raspberry pi hosting the docker 
HA container, rpi_gpio was still working. Then I stopped the container and updated it to 2022.7.3, after restarting container the missing RPi.GPIO 0.7.1 issue raised again. Tried to reboot the host again, but issue is still there.

Fortunately the manual method is still working.

**Comment by REALogics** [comment]
I updated from a 2022.6.x version to 2022.7.5.  I am using RPI 3B 32 bit.  GPIO has been working for a year.  I manually copied your rpi_gpio folder into the /config/custom_components folder.   I did not make any changes within my configuration.yaml file.  I get the same error on restart: "Requirements for rpi_gpio not found: ['RPi.GPIO==0.7.1a4']".  If I can help by providing additional information or testing, let me know.

**CONFIGURATION.YAML:**
```
# GPIO#  4  5  6  G  17 22 23 G  24  25 26 G  27 16 19 G   
# PIN #
binary_sensor:
  - platform: rpi_gpio
    invert_logic: true
    ports:
      4: Living Room Front Door
      5: Dining Room Sliding Door
      6: Laundry Room Carport Door
      17: Kitchen Window
      22: Bathroom Window
      23: Living Room Window
      24: Master Bedroom Window
      25: Guest Bedroom Window West
      26: Guest Bedroom Window North
      27: Makerspace Room Window East
      16: Makerspace Room Window North
      19: Living Room PIR

switch:
  - platform: rpi_gpio
    ports:
      2: Alarm Annunciator   
```

**SYSTEM INFORMATION:**
```
Version	core-2022.7.5
Installation Type	Home Assistant OS
Supervisor	true
Docker	true
Python Version	3.10.5
Operating System Family	Linux
Operating System Version	5.15.32-v7
CPU Architecture	armv7l
Configuration Directory	/config
Home Assistant Supervisor
Host Operating System	Home Assistant OS 8.2
Supervisor Version	supervisor-2022.07.0
Agent Version	1.2.1
Docker Version	20.10.14
Board	rpi3
```

**Comment by thecode** [comment]
> I updated from a 2022.6.x version to 2022.7.5. I am using RPI 3B 32 bit. GPIO has been working for a year. I manually copied your rpi_gpio folder into the /config/custom_components folder. I did not make any changes within my configuration.yaml file. I get the same error on restart: "Requirements for rpi_gpio not found: ['RPi.GPIO==0.7.1a4']". If I can help by providing additional information or testing, let me know.
> 

1. You have a different issue than this one.
2. From Home assistant 2022.7 and above you need a new version of the integration due to changes in the Home Assistant wheel system.

Please download the latest release from this repo, if you get an error that contains `RPi.GPIO==0.7.1a4` (note the `1a4`) you are not using the latest version. If it still doesn't work please create a new issue. Thanks

**Comment by REALogics** [comment]
Thank you for such a quick response!  Yes, all is good now!  Thank you!

**Comment by ScratMan** [comment]
https://github.com/thecode/ha-rpi_gpio/issues/83#issuecomment-1192911631

You mention the package now uses python 3.10. My RPI uses 3.7.3, I don't think it should have an impact, as HA is supposed to use it's own python environment from its container. Right ?

**Comment by thecode** [comment]
> [#83 (comment)](https://github.com/thecode/ha-rpi_gpio/issues/83#issuecomment-1192911631)
> 
> You mention the package now uses python 3.10. My RPI uses 3.7.3, I don't think it should have an impact, as HA is supposed to use it's own python environment from its container. Right ?

At least from your picture https://github.com/thecode/ha-rpi_gpio/issues/84#issuecomment-1178029469 you are using Python 3.10, if it is not the case it may explain the issue.

**Comment by ScratMan** [comment]
I discovered today that as soon as I stop, edit and then restart the HA docker container, the rpi_gpio package is gone, and I need to reinstall it manually. Even without changing nothing to the container's configuration, so it's not only when updating the image.

**Comment by thecode** [comment]
I think I understand the problem now, I was not putting attention that your docker installation might be different. You need to add an environment variable to the wheels repo
This is how it looks like in Home Assistant OS:
![image](https://user-images.githubusercontent.com/1858925/182251575-a31ca475-5c28-439e-a968-3e128a98ff56.png)

Something like `-e WHEELS_LINKS='https://wheels.home-assistant.io/musllinux/'`
Or in compose:
```yaml
  environment:
    - WHEELS_LINKS=[1](https://wheels.home-assistant.io/musllinux/)
 ```

**Comment by ScratMan** [comment]
> 

After adding the variable to the environment, I could restart the container without issue 😃 . So it seems to be fixed, I'll wait for the next update to confirm.
Thanks a lot.

**Comment by ScratMan** [comment]
> I think I understand the problem now, I was not putting attention that your docker installation might be different. You need to add an environment variable to the wheels repo This is how it looks like in Home Assistant OS: ![image](https://user-images.githubusercontent.com/1858925/182251575-a31ca475-5c28-439e-a968-3e128a98ff56.png)
> 
> Something like `-e WHEELS_LINKS='https://wheels.home-assistant.io/musllinux/'` Or in compose:
> 
> ```yaml
>   environment:
>     - WHEELS_LINKS=[1](https://wheels.home-assistant.io/musllinux/)
> ```

That definitely solved the issue. Updated to 2022.8.0 today without requiring to manually install the wheel package.

**Comment by sirjeannot** [comment]
> I think I understand the problem now, I was not putting attention that your docker installation might be different. You need to add an environment variable to the wheels repo This is how it looks like in Home Assistant OS: ![image](https://user-images.githubusercontent.com/1858925/182251575-a31ca475-5c28-439e-a968-3e128a98ff56.png)
> 
> Something like `-e WHEELS_LINKS='https://wheels.home-assistant.io/musllinux/'` Or in compose:
> 
> ```yaml
>   environment:
>     - WHEELS_LINKS=[1](https://wheels.home-assistant.io/musllinux/)
> ```

just thank you **very much**. this also solved the exact same issue on my setup.

**Comment by tazomatalax** [comment]
I am having this error after trying the suggested fixes, it still will not work
tried manually installing 

`❯ docker exec -it hass sh
root@rpi4:/# wget https://wheels.home-assistant.io/musllinux/RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl
Connecting to wheels.home-assistant.io (172.67.68.90:443)
saving to 'RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl'
RPi.GPIO-0.7.1-cp310 100% |************************************************************************| 26931  0:00:00 ETA
'RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl' saved
root@rpi4:/# pip install RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl
WARNING: The directory '/config/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: RPi.GPIO-0.7.1-cp310-cp310-musllinux_1_2_armv7l.whl is not a supported wheel on this platform.
root@rpi4:/#`

and have added

  environment:
    - WHEELS_LINKS=[1](https://wheels.home-assistant.io/musllinux/)

into my docker compose


HA version = Home Assistant 2023.10.5
Frontend 20231005.0 - latest


this is the logs entry

Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 9:11:24 AM (3 occurrences)
Last logged: 9:12:18 AM

Unable to install package RPi.GPIO==0.7.1: WARNING: Location '[1](https://wheels.home-assistant.io/musllinux/)' is ignored: it is either a non-existing path or lacks a specific scheme. error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [15 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.linux-aarch64-cpython-311 creating build/lib.linux-aarch64-cpython-311/RPi copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-311/RPi creating build/lib.linux-aarch64-cpython-311/RPi/GPIO copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-311/RPi/GPIO running build_ext building 'RPi._GPIO' extension creating build/temp.linux-aarch64-cpython-311 creating build/temp.linux-aarch64-cpython-311/source gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/config/lsiopy/include -I/usr/include/python3.11 -c source/c_gpio.c -o build/temp.linux-aarch64-cpython-311/source/c_gpio.o error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for RPi.GPIO error: subprocess-exited-with-error × Running setup.py install for RPi.GPIO did not run successfully. │ exit code: 1 ╰─> [28 lines of output] running install /config/lsiopy/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated. !! ******************************************************************************** Please avoid running ``setup.py`` directly. Instead, use pypa/build, pypa/installer or other standards-based tools. See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details. ******************************************************************************** !! self.initialize_options() running build running build_py creating build creating build/lib.linux-aarch64-cpython-311 creating build/lib.linux-aarch64-cpython-311/RPi copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-311/RPi creating build/lib.linux-aarch64-cpython-311/RPi/GPIO copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-311/RPi/GPIO running build_ext building 'RPi._GPIO' extension creating build/temp.linux-aarch64-cpython-311 creating build/temp.linux-aarch64-cpython-311/source gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/config/lsiopy/include -I/usr/include/python3.11 -c source/c_gpio.c -o build/temp.linux-aarch64-cpython-311/source/c_gpio.o error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> RPi.GPIO note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.

Does this integration just not work anymore?
