### ISSUE TITLE
Impossible to update custom component after 2022.07 Home Assistant update

### ISSUE THREAD

**Issue by flouck** [thecode/ha-rpi_gpio#85]
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:682
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: July 7, 2022 at 11:53:38 PM (2 occurrences)
Last logged: July 7, 2022 at 11:56:30 PM

The system cannot restart because the configuration is not valid: Platform error switch.rpi_gpio - Integration 'rpi_gpio' not found. Platform error switch.rpi_gpio - Requirements for rpi_gpio not found: ['RPi.GPIO==0.7.1a4'].

**Comment by Francois1976** [comment]
Probably I have the same problem cause my HA refuse to restart after update to 2022.07.  The only way to do it it's by removing the info about the rpi_gpio sensor is in the config file.

I try to remove and reinstall the integration with HACS without succes.

I read the comment #84 but I know nothing about linux and the way to use the console.  

So if a future update can solve the problem without other manipulation?

Thanks!

**Comment by thecode** [comment]
This is not something I can update as it is not something related to the integration (these are changes in the Home Assistant wheels system).
However your error shows that you are not using the correct version for core `2022.7`, if you get an error it should show `RPi.GPIO==0.7.1` without the `a4`.

What I suggest to do:
1. Roll back HA to `2022.6.x`
2. Remove the `rpi_gpio` configuration from yaml and uninstall `rpi_gpio`
3. Update HA to `2022.7.x`
4. Install the `rpi_gpio` integration again, restart and add the configuration back

**Comment by pepe59** [comment]
> Probably I have the same problem cause my HA refuse to restart after update to 2022.07. The only way to do it it's by removing the info about the rpi_gpio sensor is in the config file.
> 
> I try to remove and reinstall the integration with HACS without succes.
> 
> I read the comment #84 but I know nothing about linux and the way to use the console.
> 
> So if a future update can solve the problem without other manipulation?
> 
> Thanks!

With this problem, there is an option that also helps.
Reboot the host

**Comment by oferpaster** [comment]
Just reboot the host and the problem will be solved.

**Comment by flouck** [comment]
Indeed it worked! Thank you!

**Comment by addek83** [comment]
Worked for me as well. :-)
