### ISSUE TITLE
After rollback integration doesn't load anymore

### ISSUE THREAD

**Issue by ujaehrig** [thecode/ha-rpi_gpio#86]
I’ve seen the issue #84 , but have a slightly different configuration. 

After rolling back to 2022.6.7 (as 2022.7 has a problem with HomematicIP), I'm getting the same error as mentioned in #84. The integration was working before, though. 

As I have rolled back, I also removed the integration and reinstalled an older one. I've tried 2022.6 and 2022.4, but both give the same error: 
```
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-39
      creating build/lib.linux-aarch64-cpython-39/RPi
      copying RPi/__init__.py -> build/lib.linux-aarch64-cpython-39/RPi
      creating build/lib.linux-aarch64-cpython-39/RPi/GPIO
      copying RPi/GPIO/__init__.py -> build/lib.linux-aarch64-cpython-39/RPi/GPIO
      running build_ext
      building 'RPi._GPIO' extension
      creating build/temp.linux-aarch64-cpython-39
      creating build/temp.linux-aarch64-cpython-39/source
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-bu
iltin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.9 -c source/c
_gpio.c -o build/temp.linux-aarch64-cpython-39/source/c_gpio.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
```

my system-health shows: 
![grafik](https://user-images.githubusercontent.com/1982862/178054930-b7df0126-bfb9-480e-a277-594b975583ac.png)

The symptoms are quite similar:

1. I remove the configuration from config.yaml. 
2. I install the integration and reboot
3. As soon as I add the configuration again and execute "verify configuration", the integration is loaded and the error above is written to the log

Any idea how to fix the problem?

**Comment by thecode** [comment]
When downgrading HA you also need to downgrade the integration to [2022.6.0](https://github.com/thecode/ha-rpi_gpio/releases/tag/2022.6.0), However the Home Assistant wheels repository is currently down, I have reported it and it will be probably fixed soon.

Note that if your system can't pull the wheel from the Home Assistant wheels repository it will pull one from `PyPI` which is not precompiled and will try to compile it (which fails).
The easiest way to fix it is to upgrade and downgrade again once the wheels repository is back (you can check it at https://wheels.home-assistant.io/

**Comment by ujaehrig** [comment]
Thank you very much! The information, that wheels is down is great explanation! I will try again as soon as it's up!

**Comment by thecode** [comment]
It is back now, feel free to re-open if it is not resolved
