### ISSUE TITLE
Switch not working

### ISSUE THREAD

**Issue by MaxGeurtsen** [thecode/ha-rpi_gpio#90]
Can't get the switch to work: when i restart Hass I do here my relais going off, but when I use the switch in hass nothing happens

**Comment by thecode** [comment]
Can you provide more information? Which HA core version, what is the version of the integration, any errors in the log? Your YAML configuration for the switch.

**Comment by fantandrea** [comment]
I have a similar problem:
* upon restarting the configured GPIOs goes down
* I can control them with this plugin (e.g. turn on and off) and see the new state in the dashboard
* if I control the GPIO externally, the state is not updated i.e. I have the fan starting automatically, this plugin is not able to detected the state automatically

**Comment by thecode** [comment]
> I have a similar problem:
> 
> * upon restarting the configured GPIOs goes down
> * I can control them with this plugin (e.g. turn on and off) and see the new state in the dashboard
> * if I control the GPIO externally, the state is not updated i.e. I have the fan starting automatically, this plugin is not able to detected the state automatically
> 
> No errors logged.
> 
> Version:
> 
> * Home Assistant v2022.7.7
> * Raspberry Pi GPIO  v2022.7.0 (the one installed automatically)
> 
> I was able to have a working configuration with `command_line`:
> 
> ```yaml
>   - platform: command_line
>     switches:
>       gpio_17:
>         command_on: raspi-gpio set 17 op dh
>         command_off: raspi-gpio set 17 op dl
>         command_state: raspi-gpio get 17 | awk '{ split($3, e, "="); print e[2] }'
>         value_template: '{{ value == "1" }}'
> ```

It is not possible to set an input and output on the same GPIO. when you do it via command line you change the state of the IO from input to output. Anyhow if you have an issue it should be a new one with the requested information as in comment https://github.com/thecode/ha-rpi_gpio/issues/90#issuecomment-1207205350
