### ISSUE TITLE
upgrading  from 2022.6.6 to 2022.7.6

### ISSUE THREAD

**Issue by ferrarid61** [thecode/ha-rpi_gpio#91]
Hello,
I've tried the uprade but lots of problem since was non possible to compile GPIO. I'm using your custom from 2022.6
Can you explain me the procedure to correctly upgrade since I think you did an upgrate to the platform.
Do I have to upgrade via HACS the integration before upgrade the platform ?
Thans.

Daniele

**Comment by thecode** [comment]
2022.6 is not compatible with core 2022.7, easiest way to upgrade:
1. Comment out the integration configuration
2. Remove the integration
3. Update HA to 2022.7
4. Install latest `rpi_gpio` from HACS (currently 2022.7.0)
5. Restart HA
6. Add back the configuration and restart HA again

If you already updated HA to 2022.7 just skip step 3.

**Comment by ferrarid61** [comment]
okay, thank you so much for you immediate response.
I'm an raspy addicted and I really don't want to throw away my p3

**Comment by ferrarid61** [comment]
Hello,
I'm getting on trouble with this issue 74203 https://github.com/home-assistant/core/issues/74203 and I think I have to roll back. Is you integration compatible also with 2022.6 ? If not what I have to do to rollback ?
Thanks 
Daniele

**Comment by thecode** [comment]
> Hello, I'm getting on trouble with this issue 74203 [home-assistant/core#74203](https://github.com/home-assistant/core/issues/74203) and I think I have to roll back. Is you integration compatible also with 2022.6 ? If not what I have to do to rollback ? Thanks Daniele

You do the same as described here: https://github.com/thecode/ha-rpi_gpio/issues/91#issuecomment-1193168077
When installing the `rpi_gpio` from HACS after you downgrade Home Assistant, HACS will offer you `rpi_gpio` version [2022.6.0](https://github.com/thecode/ha-rpi_gpio/releases/tag/2022.6.0) which is compatible with HA 2022.6.

**Comment by billsmithem** [comment]
How difficult would it be (or is it possible) to support FAN as well as BINARY_SENSOR, COVER, and SWITCH? My pi4 is in a custom enclosure with SSD and definitely gets too warm without the fan running, but listening to the fan run at full speed is driving me crazy. Being able to set a percentage fan speed would be wonderful.

**Comment by thecode** [comment]
Not possible within this integration

**Comment by billsmithem** [comment]
That's a shame. I understand the maintenance issues, but removing GPIO killed a lot of functionality. If I could deal with setting it all up again I'd host it on the pi instead of letting it run the whole show. Thanks for the quick response.
