### ISSUE TITLE
OLED display support 

### ISSUE THREAD

**Issue by yousaf465** [thecode/ha-rpi_gpio#93]
Can we use this integration for OLED display to solve this issue 
https://community.home-assistant.io/t/oled-display-support-for-raspberry-pi/444268

**Comment by thecode** [comment]
No, this integration is for exposing GPIOs as Switchers or Sensors.
You need an integration that supports I2C.
I highly recommend going for an ESP solution as there many projects based on ESP.

**Comment by yousaf465** [comment]
> No, this integration is for exposing GPIOs as Switchers or Sensors. You need an integration that supports I2C. I highly recommend going for an ESP solution as there many projects based on ESP.
The ESPhome-based solution is a secondary backup but that would need a separate power supply.
