### ISSUE TITLE
RPI_GPIO Issue on HA core-2022.7.7 and rpi_gpio last version

### ISSUE THREAD

**Issue by enricochinaglia** [thecode/ha-rpi_gpio#94]
Hi, I tried with all the suggestions in other posts but still not working.
Removed the configuration, restarted
Deleted RPI_GPIO, restarted
Installed RPI_GPIO, restarted
Added configuration, restarted

Here is the error:

The following integrations and platforms could not be set up:

    [rpi_gpio](https://github.com/thecode/ha-rpi_gpio) 
    rpi_gpio.binary_sensor
    rpi_gpio.switch 

Here the configuration

switch:
  - platform: rpi_gpio
    invert_logic: true
    ports:
      5: Switch5_libero
      6: Luce sirena allarme_sw6
      13: Cicalino_inserimento_allarme_13
      19: Sirena_allarme_19
      

binary_sensor:
  - platform: rpi_gpio
    invert_logic: true
    ports:
      2: VOLUMETRICO BAGNO #GPIO2
      3: SENSORE PORTA BAGNO #GPIO3
      4: VOLUMETRICO GARAGE #GPIO4
      7: PORTA INGRESSO #GPIO7
      8: VOLUMETRICO SALA #GPIO8
      9: FREE

Can you help me?

**Comment by thecode** [comment]
It is hard to understand if your configuration is not indented correctly or not copied correctly into GitHub. Can you start with this minimal configuration and verify if it works?

```yaml
binary_sensor:
  - platform: rpi_gpio
    sensors:
      - port: 11
        name: "PIR Office"
```

**Comment by enricochinaglia** [comment]
Thank you for your reply.
I deleted the binary_sensor and replaced it with the code you wrote, same result.
![immagine](https://user-images.githubusercontent.com/5882883/181914488-7ca4fea8-11f6-4a0b-8841-d1e2e11ba477.png)

Here, the log
![immagine](https://user-images.githubusercontent.com/5882883/181914571-4c243c26-327f-4ac8-af85-759c835d87c2.png)

Hope you can understand better.
Thank you.

**Comment by thecode** [comment]
Please include the full log

**Comment by enricochinaglia** [comment]
![immagine](https://user-images.githubusercontent.com/5882883/181915767-02d069f2-3cba-417f-b579-c6e15191d2df.png)
![immagine](https://user-images.githubusercontent.com/5882883/181915790-521b69cf-0144-4882-a1a6-626690c5d342.png)

Sorry, but I can't attach here the text.

**Comment by enricochinaglia** [comment]
Hi, I solved the problem.
Was a custom integration with nodered.
Thank you for the support.
