### ISSUE TITLE
Nothing happens on GPIO

### ISSUE THREAD

**Issue by Elildar** [thecode/ha-rpi_gpio#97]
Hi,
I was using my Raspberry Pi 3b to control some buttons and switches with Node-RED on the standard RPi OS. It worked fine.
Then I flashed and installed the Home Assistant OS RPi3x64 + HACS + ha-rpi_gpio and nothing happens when I activate any button !
I've put the button on my dashboard to check it, but nothing.
If I install then Node-RED as an add-on, it is unable to receive or control any GPIO.

**Logs are empty exept :**
> 2022-08-07 11:16:58.540 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration rpi_gpio which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-07 11:16:58.546 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Here is my configuration.yaml for testing :**
\# Loads default set of integrations. Do not remove.
default_config:

\# Text to speech
tts:
  - platform: google_translate

\# Raspberry Pi GPIO Input
binary_sensor:
  - platform: rpi_gpio
    sensors:
      - port: 7
        name: "Bouton arrosage"

\# Raspberry Pi GPIO Output
switch:
  - platform: rpi_gpio
    switches:
      - port: 37
        name: "Vanne arrosage"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

**Here is my System information :**
> <html><body>

Version | core-2022.8.1
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Europe/Paris
Configuration Directory | /config

</body>
</html>
<html><body>
<div class="card-header"><h3>Home Assistant Supervisor</h3>
                

Host Operating System | Home Assistant OS 8.4
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.07.0
Agent Version | 1.2.1
Docker Version | 20.10.14
Disk Total | 6.7 GB
Disk Used | 3.5 GB
Healthy | true
Supported | true
Board | rpi3-64
Supervisor API | ok
Version API | ok
Installed Add-ons | SSH & Web Terminal (12.0.0), File editor (5.3.3)

</body>
</html>

**Comment by thecode** [comment]
Node-Red support for GPIO removed in https://github.com/hassio-addons/addon-node-red/releases/tag/v12.0.2 and is not related to this integration.

This integration use the GPIO pin# and not the header pin number:
![image](https://user-images.githubusercontent.com/1858925/183286735-41310f01-92e3-48c3-b3ed-e7f1680c20ac.png)
For example, header pin 37 is GPIO26.

Your configuration includes reference to GPIO37 which is not available and port 7 which is header pin 26.
Make sure you map them correctly.

![image](https://user-images.githubusercontent.com/1858925/183286792-b9d820e9-80cb-49de-b5fd-1af0718b2fbd.png)

**Comment by Elildar** [comment]
> This integration use the GPIO pin# and not the header pin number:
Now that you say that, it seems really obvious. I didn't realised that...
Sorry for the inconvenience and thank you for the help. I've been looking for a solution for 3 full days, and it was so simple!
Now it works fine. Home Assistant controls the GPIO and I can use the entities in Node-RED.
Thanks very much!
